# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exercicio09.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1151, 811)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEditNum = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNum.setGeometry(QtCore.QRect(400, 250, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEditNum.setFont(font)
        self.lineEditNum.setText("")
        self.lineEditNum.setObjectName("lineEditNum")
        self.labelNum_1 = QtWidgets.QLabel(self.centralwidget)
        self.labelNum_1.setGeometry(QtCore.QRect(330, 250, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.labelNum_1.setFont(font)
        self.labelNum_1.setObjectName("labelNum_1")
        self.labelDescricao = QtWidgets.QLabel(self.centralwidget)
        self.labelDescricao.setGeometry(QtCore.QRect(330, 200, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.labelDescricao.setFont(font)
        self.labelDescricao.setObjectName("labelDescricao")
        self.pushButtonVerificar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonVerificar.setGeometry(QtCore.QRect(420, 310, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButtonVerificar.setFont(font)
        self.pushButtonVerificar.setStyleSheet("background: #eaedff;")
        self.pushButtonVerificar.setObjectName("pushButtonVerificar")
        self.labelResultado = QtWidgets.QLabel(self.centralwidget)
        self.labelResultado.setGeometry(QtCore.QRect(340, 360, 381, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.labelResultado.setFont(font)
        self.labelResultado.setText("")
        self.labelResultado.setObjectName("labelResultado")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1151, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelNum_1.setText(_translate("MainWindow", "Número:"))
        self.labelDescricao.setText(_translate("MainWindow", "Digite um número para ver a tabuada dele:"))
        self.pushButtonVerificar.setText(_translate("MainWindow", "Verificar tabuada"))
