# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exercicio02.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1225, 840)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonVerificar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonVerificar.setGeometry(QtCore.QRect(440, 390, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButtonVerificar.setFont(font)
        self.pushButtonVerificar.setStyleSheet("background: #eaedff;")
        self.pushButtonVerificar.setObjectName("pushButtonVerificar")
        self.labelResultado = QtWidgets.QLabel(self.centralwidget)
        self.labelResultado.setGeometry(QtCore.QRect(370, 430, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.labelResultado.setFont(font)
        self.labelResultado.setObjectName("labelResultado")
        self.labelIdade_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelIdade_2.setGeometry(QtCore.QRect(370, 320, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.labelIdade_2.setFont(font)
        self.labelIdade_2.setObjectName("labelIdade_2")
        self.lineEditIdade = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditIdade.setGeometry(QtCore.QRect(420, 320, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEditIdade.setFont(font)
        self.lineEditIdade.setText("")
        self.lineEditIdade.setObjectName("lineEditIdade")
        self.labelIdade = QtWidgets.QLabel(self.centralwidget)
        self.labelIdade.setGeometry(QtCore.QRect(350, 270, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.labelIdade.setFont(font)
        self.labelIdade.setObjectName("labelIdade")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1225, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonVerificar.setText(_translate("MainWindow", "Verificar"))
        self.labelResultado.setText(_translate("MainWindow", "Idade "))
        self.labelIdade_2.setText(_translate("MainWindow", "Idade:"))
        self.labelIdade.setText(_translate("MainWindow", "Digite a idade para verificar se é maior de idade :"))
