# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exercicio_01.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(571, 370)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEditNum2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNum2.setGeometry(QtCore.QRect(130, 140, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEditNum2.setFont(font)
        self.lineEditNum2.setObjectName("lineEditNum2")
        self.lineEditNum1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNum1.setGeometry(QtCore.QRect(130, 80, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEditNum1.setFont(font)
        self.lineEditNum1.setObjectName("lineEditNum1")
        self.pushButtonEnviar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonEnviar.setGeometry(QtCore.QRect(150, 200, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButtonEnviar.setFont(font)
        self.pushButtonEnviar.setStyleSheet("background: #eaedff;")
        self.pushButtonEnviar.setObjectName("pushButtonEnviar")
        self.labelResultado = QtWidgets.QLabel(self.centralwidget)
        self.labelResultado.setGeometry(QtCore.QRect(20, 250, 691, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.labelResultado.setFont(font)
        self.labelResultado.setObjectName("labelResultado")
        self.labelDescricao = QtWidgets.QLabel(self.centralwidget)
        self.labelDescricao.setGeometry(QtCore.QRect(20, 30, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.labelDescricao.setFont(font)
        self.labelDescricao.setObjectName("labelDescricao")
        self.labelNum2 = QtWidgets.QLabel(self.centralwidget)
        self.labelNum2.setGeometry(QtCore.QRect(10, 140, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.labelNum2.setFont(font)
        self.labelNum2.setObjectName("labelNum2")
        self.labelNum1 = QtWidgets.QLabel(self.centralwidget)
        self.labelNum1.setGeometry(QtCore.QRect(10, 80, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.labelNum1.setFont(font)
        self.labelNum1.setObjectName("labelNum1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 571, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonEnviar.setText(_translate("MainWindow", "Enviar"))
        self.labelResultado.setText(_translate("MainWindow", "Resultado da soma: "))
        self.labelDescricao.setText(_translate("MainWindow", "Digite os números inteiros para realizar a soma:"))
        self.labelNum2.setText(_translate("MainWindow", "Segundo número:"))
        self.labelNum1.setText(_translate("MainWindow", "Primeiro número:"))
