# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'botaoPlay.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1261, 894)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonPlay = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPlay.setGeometry(QtCore.QRect(360, 170, 471, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButtonPlay.setFont(font)
        self.pushButtonPlay.setObjectName("pushButtonPlay")
        self.pushButtonPause = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPause.setGeometry(QtCore.QRect(360, 360, 471, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButtonPause.setFont(font)
        self.pushButtonPause.setObjectName("pushButtonPause")
        self.pushButtonStop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStop.setGeometry(QtCore.QRect(360, 550, 471, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButtonStop.setFont(font)
        self.pushButtonStop.setObjectName("pushButtonStop")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1261, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonPlay.setText(_translate("MainWindow", "Play"))
        self.pushButtonPause.setText(_translate("MainWindow", "Pause"))
        self.pushButtonStop.setText(_translate("MainWindow", "Stop"))
